import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, Stack, Typography } from '@mui/material';
import LogoutRoundedIcon from '@mui/icons-material/LogoutRounded';
import CloudDoneRoundedIcon from '@mui/icons-material/CloudDoneRounded';
import PersonOutlineRoundedIcon from '@mui/icons-material/PersonOutlineRounded';
import { getMe } from '../services/authService';
import type { User } from '../types';

export function SettingsPage({ logout }: { logout: () => void }) {
  const [user, setUser] = useState<User | null>(null);
  const [apiOnline, setApiOnline] = useState<boolean | null>(null);
  useEffect(() => { void getMe().then(setUser).catch(() => setApiOnline(false)); fetch('http://127.0.0.1:8000/health').then((response) => setApiOnline(response.ok)).catch(() => setApiOnline(false)); }, []);
  return <Stack spacing={3}><Box><Typography variant="h3" sx={{ fontSize: 38 }}>Settings</Typography><Typography color="text.secondary">Manage your workspace connection and account.</Typography></Box><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2 }}><Card><CardContent><Stack direction="row" alignItems="center" gap={1}><PersonOutlineRoundedIcon color="primary" /><Typography variant="h6">Account</Typography></Stack>{user ? <Stack spacing={1.5} sx={{ mt: 3 }}><Box><Typography variant="caption" color="text.secondary">Name</Typography><Typography fontWeight={700}>{user.name}</Typography></Box><Box><Typography variant="caption" color="text.secondary">Email</Typography><Typography fontWeight={700}>{user.email}</Typography></Box><Box><Typography variant="caption" color="text.secondary">Role</Typography><Chip label={user.role} size="small" /></Box><Box><Typography variant="caption" color="text.secondary">Organization</Typography><Typography fontWeight={700}>{user.organization}</Typography></Box></Stack> : <CircularProgress size={24} sx={{ mt: 3 }} />}</CardContent></Card><Card><CardContent><Stack direction="row" alignItems="center" gap={1}><CloudDoneRoundedIcon color="primary" /><Typography variant="h6">Connections</Typography></Stack><Stack spacing={2} sx={{ mt: 3 }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={700}>FastAPI backend</Typography><Typography variant="caption" color="text.secondary">http://127.0.0.1:8000</Typography></Box><Chip label={apiOnline ? 'Online' : 'Offline'} color={apiOnline ? 'success' : 'error'} size="small" /></Stack><Divider /><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={700}>Supabase project</Typography><Typography variant="caption" color="text.secondary">gfkovymkzouqbyyzfelf</Typography></Box><Chip label="Configured" color="success" size="small" /></Stack><Alert severity="info">AI and resume storage run through the protected backend. Secrets are never read by this page.</Alert></Stack></CardContent></Card></Box><Card><CardContent><Typography variant="h6">Session</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>End this browser session and return to the login page.</Typography><Button color="error" variant="outlined" startIcon={<LogoutRoundedIcon />} onClick={logout} sx={{ mt: 2 }}>Sign out</Button></CardContent></Card></Stack>;
}
